### ISSUE TITLE
Sound change automatically creates new multigraph

### ISSUE THREAD

**Issue by Alexandrathehatgirl** [bradrn/brassica#2]
I have a change [e: o:] / [jə wə] and later changes affecting w and ə. These should also affect wə sequences created by the aforementioned sound change, but they do not.

**Comment by bradrn** [comment]
This is actually expected behaviour, so not technically speaking a bug. The graphemes `jə` and `wə` without a space are treated as indivisible digraphs, no different to (say) `ng` or `th`. Thus, a change affecting `w` or `ə` should certainly not affect `wə`, since the latter is treated as a completely different phoneme. What you presumably want to do is change `e:` to `j ə` (which is two phonemes!), and similarly `o:` to `w ə`. Alas, at the moment Brassica requires this to be done in two rules:

```
e: / j ə
o: / w ə
```

Though I do admit this isn’t a great situation… and, in fact, now that I think about it, it might not be too difficult to add a syntax `[eː oː] / [{j ə} {w ə}]` or equivalent. I’ll look into it when I get some time.

**Comment by bradrn** [comment]
More than a year later, I finally got around to implementing this! As mentioned earlier, the syntax `[eː oː] / [{j ə} {w ə}]` should now do what you want.

**Comment by Alexandrathehatgirl** [comment]
Thank you very much, i don't much mind that it took you a while because now
i get the joy of being reminded of a nearly-forgotten conlanging project of
mine! (The one to which those sound changes belong).

**Comment by bradrn** [comment]
Lovely to hear!
