### ISSUE TITLE
Issue with Multi-level features not functioning properly

### ISSUE THREAD

**Issue by SKing-2003** [bradrn/brassica#6]
I can't seem to get part of the multi-level feature syntax to work, namely the syntax with '&' - having used the second example from the section on them (the one with three levels of stress), but replacing the rules given there with a simple rule `C / . / V _ V`, I found that this rule was never applied, with either of the definitions of V that were given as supposed to work (`V = +Str+None &+Str+Sec &+Str+Pri` or `V = &&Str`

![image](https://github.com/user-attachments/assets/12ef9b37-e82f-40a1-9610-4c7456dd7c8d)
![image](https://github.com/user-attachments/assets/7ce4874b-78fd-4efc-8033-6a9b107d4af1)

Apologies if I've missed something, but this was wreaking havoc on a project I'm trying to work with, so I thought I'd test it with the demonstration features in the hopes that they'd work, but it didn't. Thus, I'd like to ask if either I'm doing something wrong, or if there's an issue beyond just me that might need to be fixed?

Many thanks for this brilliant project!

**Comment by bradrn** [comment]
Thanks for the report! This is actually a known bug, which has already been fixed in commit https://github.com/bradrn/brassica/commit/2bfbe28f901307d2722c5923640de6246b91874c, although you’ll have to wait for the next release to get it. In the meantime, you can work around it by replacing that first `+Str+None` with `&+Str+None`.

As for `&&Str`, that’s not actually a bug: it’s a deliberate design decision. When there’s more than two features, there’s no one obvious way to arrange the features, so you could end up with unpredictable ordering in `V`. For this reason Brassica only supports the `&&` syntax when there are two categories. (This is documented [in the reference](https://github.com/bradrn/brassica/blob/master/docs/Reference.md#categories).)

(As it happens, these problems were already reported in https://verduria.org/viewtopic.php?p=89910#p89910, though I wouldn’t expect you to be aware of that discussion thread.)

**Comment by SKing-2003** [comment]
Many thanks! Sorry I didn't see that thread already - I don't frequent the ZBB so I didn't know this was being discussed there.
